login_user/urls.py
from django.conf.urls import url
#from login_user import views
from login_user import views
app_name = 'login_user'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^$', views.logout_user, name='logout_user'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username')]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login_user', include('login_user.urls')),
    url(r'^', include('login_user.urls') ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login_user/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

login_user/forms.py
from django import forms

from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'type':'password','placeholder':'Password','id':'p' }))
    confirmpassword = forms.CharField(widget=forms.PasswordInput(attrs={'type':'password','placeholder':'Confirm Password','id':'cp'}))
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-inline','type':'text','placeholder':'First name'}))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-inline','type':'text','placeholder':'Last name'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'type':'text','placeholder':'Username','id':'id_username'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'type':'text','placeholder':'Email'}))
    class Meta:
        model = User
        fields = ['firstname' , 'lastname','username', 'email', 'password' ,'confirmpassword'  ]

login_user/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import UserForm
from django.contrib.auth.models import User


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'auth_user/login.html')
    else:
        return render(request, 'auth_user/base_visitor.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'auth_user/login.html', context)

def validate_username(request):
    username = request.POST.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return render(request, 'auth_user/base.html')
            else:
                return render(request, 'auth_user/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'auth_user/login.html', {'error_message': 'Invalid login'})
    return render(request, 'auth_user/login.html')


def register(request):
    form = UserForm(request.POST or None)
    login_statement=None
    reg_statement=''
    if request.method == 'POST' and 'signup' in request.POST:
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirmpassword = request.POST.get('confirmpassword')
        if username is not None:
            if User.objects.filter(username=username).exists():

                reg_statement="Username already taken!"
            else:

                if password!=confirmpassword:

                    reg_statement="Password doesn't match!"
                else:#username and password are accepted
                    user = User.objects.create_user(username=username,email=email)
                    user.first_name = firstname
                    user.last_name = lastname
                    user.set_password(password)
                    user.save()
                    user = authenticate(username=username, password=password)
                    name = firstname + ' ' + lastname
                    login(request, user)

                    return render(request, 'auth_user/login.html')
    context = {
        'login_statement':login_statement,
        'reg_statement':reg_statement,
        "form": form,
    }
    return render(request, 'auth_user/register.html', context)

login_user/templates/auth_user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'auth_user/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link src="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="{% static 'auth_user/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'login_user:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav navbar-right" >
                           <li>
                    <a href="{% url 'login_user:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

login_user/templates/auth_user/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'auth_user/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'auth_user/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
             <a class="navbar-brand" href="{% url 'login_user:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
     
<ul class="nav navbar-nav navbar-right">
      <li class="{% block register_active %}{% endblock %}"><a href="{% url 'login_user:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login_user:login_user' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>

 </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

<p id="cright">
&sakkhar 2017
</p>

login_user/templates/auth_user/form_template.html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                      <script type="text/javascript" >

              </script>






<form role="form" action="" method="POST" class="registration-form">


<div style="display:inline-block;" id="apDiv1">

 <div class="panel-heading" >
Sign Up
</div>
    <div class="row">



                            <table class="spacing-table" >

                              <div class="form-group">
                               <tr >


                               <td>{{ form.firstname }} {{ form.lastname }}</td>


                               </tr>
                              </div>
                             <tr>
                             <td>
                            
                               <div class="input-group">

                               {{form.username}}
                               <div class="input-group-addon" id="lola" style="display:none"></div>
                             </div>
                           </td>





</tr>
                              <tr>


                               <td>{{ form.email }}</td>

</tr>

                              <tr>


                               <td> {{ form.password }}</td>


</tr>
                              <tr>


                               <td> {{ form.confirmpassword }}</td>


</tr>


</table>
                              <form>
                            <div class="form-group">


<select class="form-control" id="sel" required>
<option value=""selected hidden>Country</option>
<option value="AF">Afghanistan</option>
<option value="AL">Albania</option>
<option value="DZ">Algeria</option>
<option value="AS">American Samoa</option>
<option value="AD">Andorra</option>
<option value="AG">Angola</option>
<option value="AI">Anguilla</option>
<option value="AG">Antigua &amp; Barbuda</option>
<option value="AR">Argentina</option>
<option value="AA">Armenia</option>
<option value="AW">Aruba</option>
<option value="AU">Australia</option>
<option value="AT">Austria</option>
<option value="AZ">Azerbaijan</option>
<option value="BS">Bahamas</option>
<option value="BH">Bahrain</option>
<option value="BD">Bangladesh</option>
<option value="BB">Barbados</option>
<option value="BY">Belarus</option>
<option value="BE">Belgium</option>
<option value="BZ">Belize</option>
<option value="BJ">Benin</option>
<option value="BM">Bermuda</option>
<option value="BT">Bhutan</option>
<option value="BO">Bolivia</option>
<option value="BL">Bonaire</option>
<option value="BA">Bosnia &amp; Herzegovina</option>
<option value="BW">Botswana</option>
<option value="BR">Brazil</option>
<option value="BC">British Indian Ocean Ter</option>
<option value="BN">Brunei</option>
<option value="BG">Bulgaria</option>
<option value="BF">Burkina Faso</option>
<option value="BI">Burundi</option>
<option value="KH">Cambodia</option>
<option value="CM">Cameroon</option>
<option value="CA">Canada</option>
<option value="IC">Canary Islands</option>
<option value="CV">Cape Verde</option>
<option value="KY">Cayman Islands</option>
<option value="CF">Central African Republic</option>
<option value="TD">Chad</option>
<option value="CD">Channel Islands</option>
<option value="CL">Chile</option>
<option value="CN">China</option>
<option value="CI">Christmas Island</option>
<option value="CS">Cocos Island</option>
<option value="CO">Colombia</option>
<option value="CC">Comoros</option>
<option value="CG">Congo</option>
<option value="CK">Cook Islands</option>
<option value="CR">Costa Rica</option>
<option value="CT">Cote D'Ivoire</option>
<option value="HR">Croatia</option>
<option value="CU">Cuba</option>
<option value="CB">Curacao</option>
<option value="CY">Cyprus</option>
<option value="CZ">Czech Republic</option>
<option value="DK">Denmark</option>
<option value="DJ">Djibouti</option>
<option value="DM">Dominica</option>
<option value="DO">Dominican Republic</option>
<option value="TM">East Timor</option>
<option value="EC">Ecuador</option>
<option value="EG">Egypt</option>
<option value="SV">El Salvador</option>
<option value="GQ">Equatorial Guinea</option>
<option value="ER">Eritrea</option>
<option value="EE">Estonia</option>
<option value="ET">Ethiopia</option>
<option value="FA">Falkland Islands</option>
<option value="FO">Faroe Islands</option>
<option value="FJ">Fiji</option>
<option value="FI">Finland</option>
<option value="FR">France</option>
<option value="GF">French Guiana</option>
<option value="PF">French Polynesia</option>
<option value="FS">French Southern Ter</option>
<option value="GA">Gabon</option>
<option value="GM">Gambia</option>
<option value="GE">Georgia</option>
<option value="DE">Germany</option>
<option value="GH">Ghana</option>
<option value="GI">Gibraltar</option>
<option value="GB">Great Britain</option>
<option value="GR">Greece</option>
<option value="GL">Greenland</option>
<option value="GD">Grenada</option>
<option value="GP">Guadeloupe</option>
<option value="GU">Guam</option>
<option value="GT">Guatemala</option>
<option value="GN">Guinea</option>
<option value="GY">Guyana</option>
<option value="HT">Haiti</option>
<option value="HW">Hawaii</option>
<option value="HN">Honduras</option>
<option value="HK">Hong Kong</option>
<option value="HU">Hungary</option>
<option value="IS">Iceland</option>
<option value="IN">India</option>
<option value="ID">Indonesia</option>
<option value="IA">Iran</option>
<option value="IQ">Iraq</option>
<option value="IR">Ireland</option>
<option value="IM">Isle of Man</option>
<option value="IL">Israel</option>
<option value="IT">Italy</option>
<option value="JM">Jamaica</option>
<option value="JP">Japan</option>
<option value="JO">Jordan</option>
<option value="KZ">Kazakhstan</option>
<option value="KE">Kenya</option>
<option value="KI">Kiribati</option>
<option value="NK">Korea North</option>
<option value="KS">Korea South</option>
<option value="KW">Kuwait</option>
<option value="KG">Kyrgyzstan</option>
<option value="LA">Laos</option>
<option value="LV">Latvia</option>
<option value="LB">Lebanon</option>
<option value="LS">Lesotho</option>
<option value="LR">Liberia</option>
<option value="LY">Libya</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Lithuania</option>
<option value="LU">Luxembourg</option>
<option value="MO">Macau</option>
<option value="MK">Macedonia</option>
<option value="MG">Madagascar</option>
<option value="MY">Malaysia</option>
<option value="MW">Malawi</option>
<option value="MV">Maldives</option>
<option value="ML">Mali</option>
<option value="MT">Malta</option>
<option value="MH">Marshall Islands</option>
<option value="MQ">Martinique</option>
<option value="MR">Mauritania</option>
<option value="MU">Mauritius</option>
<option value="ME">Mayotte</option>
<option value="MX">Mexico</option>
<option value="MI">Midway Islands</option>
<option value="MD">Moldova</option>
<option value="MC">Monaco</option>
<option value="MN">Mongolia</option>
<option value="MS">Montserrat</option>
<option value="MA">Morocco</option>
<option value="MZ">Mozambique</option>
<option value="MM">Myanmar</option>
<option value="NA">Nambia</option>
<option value="NU">Nauru</option>
<option value="NP">Nepal</option>
<option value="AN">Netherland Antilles</option>
<option value="NL">Netherlands (Holland, Europe)</option>
<option value="NV">Nevis</option>
<option value="NC">New Caledonia</option>
<option value="NZ">New Zealand</option>
<option value="NI">Nicaragua</option>
<option value="NE">Niger</option>
<option value="NG">Nigeria</option>
<option value="NW">Niue</option>
<option value="NF">Norfolk Island</option>
<option value="NO">Norway</option>
<option value="OM">Oman</option>
<option value="PK">Pakistan</option>
<option value="PW">Palau Island</option>
<option value="PS">Palestine</option>
<option value="PA">Panama</option>
<option value="PG">Papua New Guinea</option>
<option value="PY">Paraguay</option>
<option value="PE">Peru</option>
<option value="PH">Philippines</option>
<option value="PO">Pitcairn Island</option>
<option value="PL">Poland</option>
<option value="PT">Portugal</option>
<option value="PR">Puerto Rico</option>
<option value="QA">Qatar</option>
<option value="ME">Republic of Montenegro</option>
<option value="RS">Republic of Serbia</option>
<option value="RE">Reunion</option>
<option value="RO">Romania</option>
<option value="RU">Russia</option>
<option value="RW">Rwanda</option>
<option value="NT">St Barthelemy</option>
<option value="EU">St Eustatius</option>
<option value="HE">St Helena</option>
<option value="KN">St Kitts-Nevis</option>
<option value="LC">St Lucia</option>
<option value="MB">St Maarten</option>
<option value="PM">St Pierre &amp; Miquelon</option>
<option value="VC">St Vincent &amp; Grenadines</option>
<option value="SP">Saipan</option>
<option value="SO">Samoa</option>
<option value="AS">Samoa American</option>
<option value="SM">San Marino</option>
<option value="ST">Sao Tome &amp; Principe</option>
<option value="SA">Saudi Arabia</option>
<option value="SN">Senegal</option>
<option value="RS">Serbia</option>
<option value="SC">Seychelles</option>
<option value="SL">Sierra Leone</option>
<option value="SG">Singapore</option>
<option value="SK">Slovakia</option>
<option value="SI">Slovenia</option>
<option value="SB">Solomon Islands</option>
<option value="OI">Somalia</option>
<option value="ZA">South Africa</option>
<option value="ES">Spain</option>
<option value="LK">Sri Lanka</option>
<option value="SD">Sudan</option>
<option value="SR">Suriname</option>
<option value="SZ">Swaziland</option>
<option value="SE">Sweden</option>
<option value="CH">Switzerland</option>
<option value="SY">Syria</option>
<option value="TA">Tahiti</option>
<option value="TW">Taiwan</option>
<option value="TJ">Tajikistan</option>
<option value="TZ">Tanzania</option>
<option value="TH">Thailand</option>
<option value="TG">Togo</option>
<option value="TK">Tokelau</option>
<option value="TO">Tonga</option>
<option value="TT">Trinidad &amp; Tobago</option>
<option value="TN">Tunisia</option>
<option value="TR">Turkey</option>
<option value="TU">Turkmenistan</option>
<option value="TC">Turks &amp; Caicos Is</option>
<option value="TV">Tuvalu</option>
<option value="UG">Uganda</option>
<option value="UA">Ukraine</option>
<option value="AE">United Arab Emirates</option>
<option value="GB">United Kingdom</option>
<option value="US">United States of America</option>
<option value="UY">Uruguay</option>
<option value="UZ">Uzbekistan</option>
<option value="VU">Vanuatu</option>
<option value="VS">Vatican City State</option>
<option value="VE">Venezuela</option>
<option value="VN">Vietnam</option>
<option value="VB">Virgin Islands (Brit)</option>
<option value="VA">Virgin Islands (USA)</option>
<option value="WK">Wake Island</option>
<option value="WF">Wallis &amp; Futana Is</option>
<option value="YE">Yemen</option>
<option value="ZR">Zaire</option>
<option value="ZM">Zambia</option>
<option value="ZW">Zimbabwe</option>
</select>
                          </form>



                    <div class="form-group" id="sub" >

                        <button type="submit" name="signup" class="btn" id="btn1" >Create an account</button>

                   </div>



                 </div>

       </div>
 <div class="panel-footer">

                          Already have an account? <a href="{% url 'login_user:login_user' %}">Click here</a> to log in.

                     </div>

 </div>

</div>

login_user/templates/auth_user/index.html
{% block body %}
<h>this is me</h>
{% endblock %}

login_user/templates/auth_user/login.html
{% extends 'auth_user/base_visitor.html' %}

{% block title %}Login{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}


<form role="form" action="" method="POST" class="login-form">

                             {% csrf_token %}

<div style="display:inline-block;" id="apDiv1">

 <div class="panel-heading" >
Sign In
</div>
    <div class="row">



                            <table class="spacing-table" >

                              <div class="form-group">

                              </div>
                             <tr>
                               <td><input id="id_username" maxlength="30" name="username" type="text" placeholder="Username" required></td>

</tr>


                              <tr>


                               <td><input id="id_password" maxlength="30" name="password" type="password" placeholder="Password" required ></td>

</tr>
                              <tr>




</table>
  <div class="form-group" id="sub" >

                        <button type="submit" class="btn" id="btn2" >Login</button>

                   </div>



                 </div>

       </div>
{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                                                  {% endblock %}


}

login_user/templates/auth_user/register.html
{% extends 'auth_user/base_visitor.html' %}

{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}



<form role="form" action="" method="POST" class="registration-form">

  {% csrf_token %}

{% include 'auth_user/form_template.html' %}

{{reg_statement}}

      {% block javascript %}
      <script>
      console.log($("#id_username"));
    $("#id_username").keyup(function() {


      if (this.value.length < 4) {
        $("#lola").hide();
        return
      }
      $("#lola").show();
      var username = $(this).val();
      console.log(username);
      $.ajax({
        url: '/ajax/validate_username/',
        type: "POST",
        data: {
          'username': username,
          csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        dataType: 'json',
        success: function(data) {
          console.log(data);
          if (data.is_taken) {
            $("#lola").html('<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>');
          

          } else {
            $("#lola").html('<i class="glyphicon glyphicon-ok" aria-hidden="true"></i>');
          }
        }
      });

    });
    </script>
      {% endblock %}
{% endblock %}